# Generated by Django 4.2.4 on 2023-08-25 14:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_advertisements_V2', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TempUser',
        ),
    ]
